//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armazem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Armazem()
        {
            this.ArtigoArmazems = new HashSet<ArtigoArmazem>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> designacao { get; set; }
        public Nullable<int> idLocalizacao { get; set; }
        public Nullable<System.Guid> createOn { get; set; }
        public Nullable<System.Guid> removeOn { get; set; }
        public Nullable<System.Guid> createBy { get; set; }
    
        public virtual Localizacao Localizacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtigoArmazem> ArtigoArmazems { get; set; }
    }
}
