//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Artigoes = new HashSet<Artigo>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Pessoas = new HashSet<Pessoa>();
        }
    
        public System.Guid id { get; set; }
        public string designacao { get; set; }
        public string nuit { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public string pessoaContacto { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public Nullable<System.DateTime> removeOn { get; set; }
        public Nullable<System.Guid> idLocalizacao { get; set; }
        public Nullable<System.Guid> createBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoas { get; set; }
    }
}
