//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.ArtigoPessoas = new HashSet<ArtigoPessoa>();
        }
    
        public System.Guid id { get; set; }
        public string nome { get; set; }
        public Nullable<System.Guid> idTipoPessoa { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public Nullable<System.Guid> idEmpresa { get; set; }
        public string endereco { get; set; }
        public Nullable<int> idLocalizacao { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public Nullable<System.DateTime> removeOn { get; set; }
        public Nullable<System.Guid> createBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtigoPessoa> ArtigoPessoas { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Localizacao Localizacao { get; set; }
        public virtual TipoPessoa TipoPessoa { get; set; }
    }
}
